/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnitImport } from './routes/unit'
import { Route as ItemImport } from './routes/item'
import { Route as InventoryImport } from './routes/inventory'
import { Route as FreezerImport } from './routes/freezer'
import { Route as CategoryImport } from './routes/category'

// Create/Update Routes

const UnitRoute = UnitImport.update({
  path: '/unit',
  getParentRoute: () => rootRoute,
} as any)

const ItemRoute = ItemImport.update({
  path: '/item',
  getParentRoute: () => rootRoute,
} as any)

const InventoryRoute = InventoryImport.update({
  path: '/inventory',
  getParentRoute: () => rootRoute,
} as any)

const FreezerRoute = FreezerImport.update({
  path: '/freezer',
  getParentRoute: () => rootRoute,
} as any)

const CategoryRoute = CategoryImport.update({
  path: '/category',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryImport
      parentRoute: typeof rootRoute
    }
    '/freezer': {
      id: '/freezer'
      path: '/freezer'
      fullPath: '/freezer'
      preLoaderRoute: typeof FreezerImport
      parentRoute: typeof rootRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryImport
      parentRoute: typeof rootRoute
    }
    '/item': {
      id: '/item'
      path: '/item'
      fullPath: '/item'
      preLoaderRoute: typeof ItemImport
      parentRoute: typeof rootRoute
    }
    '/unit': {
      id: '/unit'
      path: '/unit'
      fullPath: '/unit'
      preLoaderRoute: typeof UnitImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  CategoryRoute,
  FreezerRoute,
  InventoryRoute,
  ItemRoute,
  UnitRoute,
})

/* prettier-ignore-end */
